-- Jalankan SQL ini di Supabase SQL Editor.

create table if not exists loans (
  id bigint generated by default as identity primary key,
  member_name varchar(100) not null,
  book_title varchar(200) not null,
  borrow_date date not null,
  due_date date not null,
  return_date date,
  status varchar(30) not null check (status in ('Dipinjam', 'Dikembalikan', 'Terlambat')),
  created_at timestamptz default now()
);

-- Data contoh
insert into loans
(member_name, book_title, borrow_date, due_date, return_date, status)
values
('Andi Saputra', 'Pemrograman JavaScript', '2026-09-20', '2026-09-27', null, 'Terlambat'),
('Budi Santoso', 'Dasar Jaringan Komputer', '2026-09-25', '2026-10-02', null, 'Dipinjam'),
('Citra Lestari', 'Algoritma dan Pemrograman', '2026-09-15', '2026-09-22', '2026-09-21', 'Dikembalikan');
